service: default
runtime: go
api_version: go1

handlers:
- url: /assets/
  static_dir: assets

- url: /bootstrap3/
  static_dir: bootstrap3

- url: /jquery/
  static_dir: jquery

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app
